apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: bcast-two-nodes
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiImplementation: MPICH
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: localhost/my-osu-bench:latest
            imagePullPolicy: Never
            name: osu-launcher
            securityContext:
              runAsUser: 1000
            args:
            - mpirun
            - -n
            - "2"
            - /home/mpiuser/osu/libexec/osu-micro-benchmarks/mpi/collective/osu_bcast
            - -f
            - -z
            - -i
            - "10000"
            - -m
            - "4194304"
    Worker:
      replicas: 2
      template:
        metadata:
          labels:
            app: osu-worker
        spec:
          containers:
          - image: localhost/my-osu-bench:latest
            imagePullPolicy: Never
            name: osu-worker
            securityContext: 
              runAsUser: 1000
            command:
            args:
            - /usr/sbin/sshd
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            readinessProbe:
              tcpSocket:
                port: 2222
              initialDelaySeconds: 2
          topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app: osu-worker